version: '3'
services:
  postgres:
    image: postgres:13
    container_name: weather_project
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data